### ISSUE TITLE
US-6_Labels-to-axes

### ISSUE THREAD

**Issue by MariaAdner** [catdieval/capstone-plotdata#10]
# Labels-to-axes

## Value Proposition
As a user I want to give labels to the x- und y-axis to have a descriptive plot of my data.

## Description 

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/20694458-5fb4-4806-9e4d-20210a70919d)

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/2539ab6a-7a79-4a25-9cff-27f0ba63bc2b)

## Acceptance Criteria

- [x] Paragraph with text "Step 4: give labels to the axes".
- [x] Paragraph with text "For the x variable you chose:" + xKey value (reminder).
- [x] Paragraph with text "For the y variable you chose:" + yKey value (reminder).
- [x] Paragraph with text "Label for the x-axis:"
- [x] Input of type "text" where the user can enter the label for the x-axis. In the input is a placeholder text to guide the user.
- [x] Paragraph with text "Label for the y-axis:"
- [x] Input of type "text" where the user can enter the label for the y-axis. In the input is a placeholder text to guide the user.
- [x] A "Next" button to confirm what the user has written in the form. The button stays disabled until the user has entered a value for the y-axis label.
- [x] The plot gets updated with the labels to the axes.

## Tasks

- [x]  Create a new feature branch "Labels-to-axes"

- [x] Create an InputTypeText component:
  - [x] The function has for argument the placeholderString prop, the onChange prop and the idString prop. 
  - [x] The function renders a label element and an input of type "text".
  - [x] The input has the required attribute and has the placeholder attribute set to placeholderString as prop and the onChange attribute set to onChange as prop.
  - [x] The idString prop is used as value for the other attributes of label and of input.
  
- [x]  Create a XandYLabelsGraph component.
  - [x] Hard code the xKey and the yKey variables 
  - [x] useState for the xLabel and the yLabel variables with default value set to "".
  - [x] Declare a handleSubmit function which does event.preventDefault() .  
  - [x] Declare handleXLabelChange / handleYChange functions which set setXLabel / setYLabel to event.target.value 
  - [x] Declare a handleAxesLabels function which sends an alert with the text set to "Labels for the x-axis and the y-axis of the graph are assigned".
  - [x] Declare a completedXandYLabels function to disable the "Next" button until the user has entered values in all input fields.
  - [x] The component renders 2 instances of Paragraph and a form.
  - [x] Inside the form are nested two instances of the InputTypeText component and the StyledInputTypeSubmit component.
  - [x] The form takes the handleSubmit function as prop to the onSubmit attribute.
  - [x] The first / second InputTypeText takes "Fill me with name and unit, e.g. Age (years)" / "Fill me with name and unit, e.g. Height (inches)" as prop to the placeholderString attribute and the handleXLabelChange / handleYLabelChange function as prop to the onChange attribute and "Label for the x-axis" /  "Label for the y-axis" prop to the idString attribute.
  - [x] The StyleInputTypeSubmit component with "Next" as value to the value attribute, the handleAxesLabels function as value to the onClick attribute and completedXandYLabels() as value to the disable attribute.

- [x] In the Plotting Component, access xLabel and yLabel.
  - [x] Use xLabel / yLabel != "" as additional conditions for the rendering of the Plot component.
  - [x] Set xLabel / yLabel as value to the title key of the x-axis / y-axis in the layout attribute of the Plot component.
  
- [x] Add the XandYLabelsGraph component to the index.js file (after the ListOfCharts component).
