### ISSUE TITLE
US-X_Labels-to-legend

### ISSUE THREAD

**Issue by MariaAdner** [catdieval/capstone-plotdata#11]
# Labels-to-legend

## Value proposition

As a user I want to set a label for the legend of my data to improve my plot. 

## Acceptance Criteria

- [ ] Layout as in the description
- [ ] User has a form where he can type the label for each y variable. This form is only rendered after the user has added new y variables. In each input field is a placeholder text to guide the user.
- [ ] A "Submit"-Button to confirm what the user has written in the form

## Tasks

- [ ] Create a feature branch "Labels-to-legend"
- [ ] Create a Legend Component:
  - [ ] Form with several inputs of type "text", whose number is equal to the number of y variables.
  - [ ] A yVariablesLabels variable is defined as an array with length corresponding to the number of y variables. Each element is set to the value of the corresponding input. Mapping is needed.
  - [ ] Button with handleLegend function, which saves the yVariableLabels to the local storage
- [ ]  In the Plotting component, for each object in the data attribute of the Plot component: set the value of the name key to the corresponding value from the yVariablesLabels array, like `name: yVariablesLabels[index],` . Mapping is needed.
