### ISSUE TITLE
US-7_Graph-title

### ISSUE THREAD

**Issue by MariaAdner** [catdieval/capstone-plotdata#12]
# Graph-Title

## Value proposition

As a user I want to give a title to the graph to better understand what the plot is about.

## Description

![Image](https://github.com/catdieval/capstone-plotdata/assets/148149765/c7900c8c-0847-4eb3-91b7-01f1aa58394a)

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/9656085a-eee4-4196-82d6-d23af0ea8cfd)

## Acceptance Criteria
 - [x] Title with logo at the top of the page.
 - [x] A paragraph with text "Label for the x-axis:".
 - [x] A paragraph with the value entered by the user for the x label.
 - [x] A paragraph with text "Label for the y-axis:".
 - [x] A paragraph with the value entered by the user for the y label.
 - [x] A paragraph with text "Title:".
 - [x] An input of type "text" where the user can enter the title of the graph. The input has a placeholder text to guide the user.
 - [x] A "Next" button to send an alert message with text "Title of the graph is assigned". The button stays disabled until the user has entered a value for the title.
 - [x] The plot gets updated with the title.

## Tasks

- [x]  Create a feature branch "Graph-title".

- [x]  Create a `GraphTitle` component.
  - [x] Access `xLabel` and `yLabel` variables.
  - [x] `useState` for the `titleLabel` variable with initial value set to "".
  - [x] Declare a `handleSubmit` function which does event.preventDefault() .  
  - [x] Declare a `handleTitleChange` function which sets `setTitleLabel` to `event.target.value`.
  - [x] Declare a `handleTitle` function which sends an alert message.
  - [x] Write a `completedTitle` function to disable the "Next" button until the user has entered a value for the title.
  - [x] The component renders 4 instances of `Paragraph` and a `form`.
  - [x] Inside the `form` is nested the `Container` component, and inside of it are nested the `InputTypeText` component and the `StyledInputTypeSubmit` component.
  - [x] The `Container` component has the $centered attribute set to "center".
  - [x] The form takes the handleSubmit function as prop to the onSubmit attribute.
  - [x] The second Paragraph has for text xLabel.
  - [x] The fourth Paragraph has for text yLabel.  
  - [x] The InputTypeText takes "Fill me with title" as prop to the placeholderString attribute and the handleTitleChange function as prop to the onChange attribute and "Title" as prop to the idString attribute.
  - [x] The StyleInputTypeSubmit component has "submit" as value to the type attribute, "Next" as value to the value attribute, the handleTitle function as value to the onClick attribute and completedTitle() as value to the disable attribute.

- [x] In the Plotting Component, access titleLabel.
  - [x] Use titleLabel != "" as additional condition for the rendering of the Plot component.
  - [x] Set titleLabel as value to the title key in the layout attribute of the Plot component.
  
- [x] Add the GraphTitle component to the index.js file (before the Plotting component).
