### ISSUE TITLE
US-8-Line-properties

### ISSUE THREAD

**Issue by MariaAdner** [catdieval/capstone-plotdata#13]
# Line-properties

## Value proposition
As a user
I want to set the properties of the curve in the plot
so that I can change the visual display.

## Description

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/d77268b3-e02e-4d25-bc43-8d1681bb63a0)

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/957d484f-eeb1-4bb1-ac14-b42c57617869)

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/90dbd806-78c5-4878-b309-9b0b8cd83402)

## Acceptance Criteria

- [x] The component is displayed only if the user chose "line-plot".
- [x] Heading with text "Line properties".
- [x] Paragraph with text "Line color".
- [x] The user can choose from a dropdown menu the color of the line, options: red/blue/green/yellow/orange/pink/purple/maroon/black/grey. 
- [x] Paragraph with text "Line style".
- [x] The user can choose from a dropdown menu the linestyle, options: solid, dash, dot, longdash, dashdot.
- [x] Paragraph with text "Line width (in pixels)".
- [x] The user can choose from a dropdown menu the thickness of the line, options: 1, 2, 3, 4, 5. 
- [x] "Next" button which stays disabled until the user has selected a value for the line width.
- [x] When the user clicks on the "Next" button, an alert message is displayed "You chose the line properties.". 
- [x] If the user chose "line-plot" then the plot gets updated with the line properties.

## Tasks

- [x] Create a new feature branch "Line-properties".

- [x] In the lib folder create a `listOfLineProperties.js` file.
  - [x] Declare a `lineColorArray`, a `lineStyleArray` and a `lineWidthArray` arrays.
  - [x] `lineColorArray` / `lineStyleArray` / `lineWidthArray` contain the color / style / width options.
  
- [x] Create a `LineProperties` component.
  - [x] Access titleLabel.
  - [x] useState for the `lineColor / lineStyle / lineWidth` variable with initial value set to "" / "" / 0.
  - [x] Declare a `handleLineColorChange / handleLineStyleChange / handleLineWidthChange` function which declares a choice variable set to event.target.value.
  - [x] Declare a `handleLineProperties` function with an alert message.
  - [x] Write a `handleSubmit` function which does event.preventDefault().
  - [x] Declare a `completedLineProperties` function to disable the "Next" button until the user has selected values in all dropdown menus.
  - [x] The function returns the `Heading` component and a form. 
  - [x] The form takes the `handleSubmit` function as prop to the `onSubmit` attribute.
  - [x] Inside the form is nested the `Container` component, and inside of it 3 instances of the `DropDownMenu` component and the `StyledInputTypeSubmit` component.
  - [x] The `Container` component has the $centered attribute set to "center".
  - [x] The first / second / third render of `DropDownMenu` has "Line color" / "Line style" / "Line width" as prop to the `idString` attribute and the `handleLineColorChange / handleLineStyleChange / handleLineWithChange` function as prop to the `onChange` attribute and `lineColorArray / lineStyleArray / lineWidthArray` as prop to the `arrayOfOptions` attribute. 
  - [x] The `StyleInputTypeSubmit` component has "Next" as value to the value attribute, the `handleLineProperties` function as value to the `onClick` attribute and the disabled attribute set to `completedLineProperties()`.

  - [x] Use conditional rendering in the return to display the output only if titleLabel.length > 0 and if `clickedChartType = "line-plot"`.
  
- [x]  In the index.js file, add the `LineProperties` component (before the Plotting component).  

- [x] In the `Plotting` component, access the `lineColor, lineStyle and lineWidth` variables.
  - [x] If `clickedChartType="line-plot"`, declare as var a dataOptions variable like `dataOptions = {
      x: xVariable,
      y: yVariable,
      mode: selectedMode,
      type: selectedType,
      line: {
        color: lineColor,
        dash: lineStyle,
        width: lineWidth,
      },
    }`.
  - [x] In the return of the function, add a conditional expression with ternary operator between : and null, like X ? Y :  , where X is a copy of the conditional statement and Y is a copy of the Plot render.
  - [x] In the first render of Plot replace the value of the data attribute by {[dataOptions]} and in the first conditional expression add `lineStyle.length > 0` as additional condition.

/

**Comment by NikRoe** [comment]
Hi there,

your value proposition can be a less specific. You can go into more detail in your Acceptance Criteria.

Your VP can look like this:
As a user 
I want to set the properties of the curve in the plot 
so that I can change the visual display.

Apart from that, this user story looks really nice.

(Although you don't have to be that specific and detailed when writing your Tasks)

--> User Story is approved, but please shorten the VP to something similar to my suggestion.

Keep it up 🙌
