### ISSUE TITLE
US-9-Markers-properties

### ISSUE THREAD

**Issue by MariaAdner** [catdieval/capstone-plotdata#14]
# Markers-properties

## Value proposition
As a user I want to set the properties (color, symbol, size) of my scatter plot to have a nice plot of my data.

## Acceptance Criteria

- [ ] User can choose from a dropdown menu the color of the makers 
- [ ] User can choose from a dropdown menu the symbol of the makers
- [ ] User can choose from a dropdown menu the size of the markers

## Tasks

- [ ] Create a new feature branch "Markers-properties"
- [ ] Create a MarkersProperties component
  - [ ] 3 Dropdown menus:
    - [ ] 1.) Marker color:
    - [ ] 2.) Marker symbol
    - [ ] 3.) Marker size:
 - [ ] This component is only rendered in the index.js - file if the user has selected a graph as markers-plot

**Comment by NikRoe** [comment]
Hi there,

nice user story.

You can shorten your value proposition to something like this:
As a user 
I want to set the properties of the markers my plot 
to have the option to change the visual display of my data.

Apart from that, nicely done 👏 

--> please change the value proposition to something similar to my suggestion. (US is approved)
