### ISSUE TITLE
US-15-Plotting-properties

### ISSUE THREAD

**Issue by MariaAdner** [catdieval/capstone-plotdata#15]
# Plotting properties

## Value proposition
As a user 
I want to make preferences for the style and the layout of my plot
So that I can have a nice plot.

## Description

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/e78b1071-2e83-420e-a9e9-d3e929e7c060)

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/f29bb295-2ec7-4a59-bb61-c0b375e1b41c)

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/dcf9d3c6-84f8-4c33-8a85-2765ea6f34a7)

## Acceptance criteria

- [x] Title with logo at the top pf the page.
- [x] Paragraph: "Step 6: Assign properties to the graph".
- [x] If the user clicked **line-plot**, then the line properties are displayed.
- [x] If the user clicked **scatter-plot** or **line-markers-plot**, then the marker properties are displayed.
- [x] If the user clicked **bar-plot**, then the bar properties are displayed.
- [x] The layout properties are displayed.
- [x] The plot gets updated with the layout properties and with the relevant category of graph properties.

## Tasks

- [x] Create a new feature branch "Plotting-properties".

- [x] Create a PlottingProperties Component:
  - [x] It returns Heading, LineProperties, MarkerProperties, BarProperties and LayoutProperties.
  - [x] The Heading takes "Step 6: Assign properties to the graph" for text.

- [x] In the index.js, add the PlottingProperties component (before Plotting) and remove MarkerProperties, BarProperties, LineProperties and LayoutProperties from the return.

(The storing and the processing of the selected properties are detailed in US 8 - Line Properties, US 9 - Marker Properties, US 10 - Bar properties, US 11 - Layout grid properties, US 12 - Layout range properties, US 13 - Layout log scale properties and US 14 - Layout properties)

**Comment by F-Kirchhoff** [comment]
This looks quite good! Can you please give more information in the tasks how you store and process the selected properties? Otherwise the user story is ready to go.
