### ISSUE TITLE
US-10-Bar-properties

### ISSUE THREAD

**Issue by MariaAdner** [catdieval/capstone-plotdata#17]
# Bar properties

## Value proposition
As a user I want to 
set the properties of the bars in the plot
so that I can update the visual display.

## Description

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/b3e86fe9-8905-48cd-ac38-900f4c8a5e9a)

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/2cbaaf6b-84f3-47d4-b3b9-d8362093ba0c)

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/2f9fb7f1-f411-45b4-9951-f18a51abe660)

## Acceptance Criteria

- [x] The component is displayed only if the user chose "bar-plot".
- [x] Heading "Bar properties".
- [x] Paragraph "Bar color".
- [x] User can choose from a dropdown menu the color of the bars, options: red, blue, green, yellow, orange, pink, purple, maroon, black, grey. 
- [x]  "Next" button which stays disabled until the user has selected a value from the dropdown menu.
- [x] When the user clicks on the "Next" button, an alert message is displayed "You chose the bar properties.".
- [x] Plot gets updated with the bar properties (only if the user has clicked "bar-plot").

## Tasks

- [x] Create a new feature branch "Bar-properties".

- [x] In the `lib` folder create a `listOfBarProperties.js` file.
  - [x] Declare a `barColorArray` array with the options for the color.
  
- [x] Create a  `BarProperties`Component.
  - [x] Access titleLabel.
  - [x] `useState` for the barColor. 
  - [x] Declare a `handleBarColorChange` function which declares a choice variable set to event.target.value.
  - [x] Declare a `handleBarProperties` function with an alert message.
  - [x] Declare a `completedBarPoperties` function to disable the "Next" button until the user has selected the value in the dropdown menu.
  - [x]  Write  `handleSubmit` function which does event.preventDefault().
  - [x] Returns  a `Heading` and  a `form` (prop  `handleSubmit`) with a `Container`($centered set to "center") nested in it and inside are the `Paragraph`, `DropDownMenu` and `StyledInputTypeSubmit` components nested into it.
  - [x] Use conditional rendering in the return to display the output only if titleLabel.length > 0 and if `clickedChartType = "bar-plot" `.

- [x] In the index.js file, add the `BarProperties` component (before the `Plotting` component).

- [x] In the `Plotting` component, access the barColor variable.
  - [x] If clickedChartType="bar-plot", declare as var a dataOptions variable like `dataOptions = {
  x: xVariable,
  y: yVariable,
  mode: selectedMode,
  type: selectedType,
  marker: {
    color: barColor,
  },
}`.
  - [x] In the return of the function, add a conditional expression with ternary operator between : and null, like X ? Y : , where X is a copy of the conditional statement and Y is a copy of the Plot render.
  - [x] In the first render of Plot replace the value of the data attribute by {[dataOptions]} and in the first conditional expression add barColor.length > 0 as additional condition.
