### ISSUE TITLE
US-2_select-plot-type

### ISSUE THREAD

**Issue by catdieval** [catdieval/capstone-plotdata#2]
# Select a plot type

## Value Proposition
As a user I want to see a list with graph types
so I can choose the one I need.

## Description

![Image](https://github.com/catdieval/capstone-plotdata/assets/148149765/e9984eae-0e06-45d0-9d79-d03ef2e1bc6b)

## Acceptance Criteria
- [x] Title at the top with the name of the website and a logo.
- [x] Heading with text "Step 2: Decide what type of graph.".
- [x] List of images corresponding to examples of each type of chart, with corresponding button named after the type of chart.
- [x] Clicking on the button for a chart type sends an confirmation message.

## Tasks
- [x]  Create a feature branch "select-chart-type".
- [x] Create a chart-types folder in the public folder with icon images corresponding to each type of plot (line plot, scatter plot, line+markers plot, bar plot).
- [x] Create a lib folder and a listOfPlotTypes.js file inside which declares an chartArray array which contains objects with the keys "type", "mode", "icon" and "name".
    - [x]  The type key has for value a string corresponding to the name of the type of chart (e.g. "scatter", "bar").
    - [x] The mode key has for value a string corresponding to the name of the type of plotting mode (e.g. "lines", "markers", "lines+markers").
    - [x] The name key has for value a string corresponding to the name of the associated picture contained in the chart-types folder.
    - [x] The icon key has for value the path of the image.
- [x]  Create a FlexContainer component which takes as prop flex-direction.

- [x] Create a ChartItem component.
   - [x] The ChartItem function takes for argument the prop name.
   - [x] Declare a local storage state for the clickedChartType variable, with "" as default value.
   - [x] Write an handleClick function, taking element as argument.
   - [x] This function sets setClickedChartType to element.target.innerText.
   - [x] The ChartItem function returns, within the FlexContainer component, the Button component and the Image component.
   - [x] FlexContainer takes row as prop for the flex-direction attribute.
   - [x] Image takes an src attribute set to the path of the associated picture and an alt attribute set to the name prop.
   - [x] The Button of type "button" takes an onClick attribute which has handleClick as prop. The text of the button is the name prop.
- [x] Create a ListOfCharts component.
  - [x] The function returns a fragment, and nested within, the Heading component and the FlexContainer component.
  - [x] FlexContainer takes row as prop to the flex-direction attribute.
  - [x] Heading has for text "Step 2: Decide what type of chart.".
  - [x] Nest curly brackets within the FlexContainer, where you use map over chartArray to render the ChartItem component.
  - [x] Give the key name as prop to ChartItem.
- [x] In the index.js file, the Homepage function returns the ListOfCharts component.

//

**Comment by MerleMak** [comment]
Hey team!
Nice User story! Some comments:
I think this point is not useful:
- Clicking on the button for a chart type shows an alert message to inform the user which type of chart was selected.
I think this will be more irritating for the user than helpful. Instead, you could just be highlighting the button that has been selected with a shaded color or something similar, but alerts should only be used on very specific occasions. 

What are these two tasks for?

- Create a FlexRowDiv component.
- Create a FlexColumnDiv component.
   -> maybe its better to use a grid here? https://css-tricks.com/snippets/css/complete-guide-grid/

For this:
- Create a Img component.
   -> better use the Next Image component

For this:
- Declare an handleClick function, taking event as argument and which sets setClickedChartType to event.target.value and which calls an alert function with the text You chose "${clickedChartType}".
   -> Either highlight the respective button like i said before, or render a p Tag with this text instead of an alert:

Great job with this, keep it going 😊
