### ISSUE TITLE
DS-Refactor the code for the selected button

### ISSUE THREAD

**Issue by YavorLalev** [catdieval/capstone-plotdata#22]
## Value proposition

As a developer I need to refactor the code so that it can improve the overall performance of the App.

## Acceptance Criteria
 - [x] When the user selects the type of graph the button should stay highlighted  even if the user clicks on other elements of the App.

## Tasks

- [x]  Create a feature branch ds-refactor-selected-button.
- [x]  In App.js refactor the `handleChartType()`.
- [x]  Pass  down`clickedChartType` prop to the `ListOfCharts`, `Button`& `ChartItem` components.
- [x]  Create `isActive` prop in the`Button`component.
- [x]  Use `isActive` prop to toggle via ternary operator the background color for the selected button.
