### ISSUE TITLE
US-11-Layout-Grid-Properties

### ISSUE THREAD

**Issue by MariaAdner** [catdieval/capstone-plotdata#29]
# Layout Properties

## Value description
As a user I want to have the possibility to chose to have a grid for the x-and y-axis and determine the line-style of the grid.

## Description

![Image](https://github.com/catdieval/capstone-plotdata/assets/148491107/b1a5e514-0680-4144-bfe2-fbcba4f62f0f)

## Acceptance Criteria
- [ ] Heading with text "Layout properties".
- [ ] Paragraph with text "Show grid (helper lines) for axes:".
- [ ] User can decide to have a grid separately for the x- and y-axis by using radio-buttons ("yes"/"no").
- [ ] Only when the user clicked yes on the radio buttons above:
  - [ ] Paragraph with text "Grid linestyle:".
  - [ ] User can choose from two dropdown-menus the grid linestyle for the x- and y-axis, options are: solid, dash, dot, longdash, dashdot.
 - [ ] "Next" button which stays disabled until the user has entered values in all the fields.
- [ ] The plot gets updated with the layout properties.

## Tasks

- [ ] Create a new feature branch "Layout-grid-properties".

- [ ] Create a component `InputTypeRadio`
  - [ ] function with props `label`, `value`, `name` ,`id` and `onChange`
  - [ ] returns `label` and `input`
 
- [ ] Create a component `LayoutProperties`
  - [ ] Declare the `useState` and handle-functions for all properties: 
    - `gridXAxis` ,  `gridYAxis`
    -  `gridLineStyleXAxis` , `gridLineStyleYAxis`
  
   - [ ] Declare a `handleSubmit` function which does `event.preventDefault()` .
   - [ ] Declare a `completedLayout` function to disable the "Next" button until the user has chosen all 
    values 
   - [ ] Return: `Heading`, `Paragraph`, `form`, `InputTypeRadio`, `StyledInputTypeSubmit` components in the appropriate order and text described in the acceptance criteria 

-  [ ]  In the `Plotting` component access all property variables
   - [ ] according to the choice of the user add the attributes to the object of the axis in the layout object of the Plot:  `layout={{
                xaxis: {
                  title: { text: xLabel },
                  showgrid: false,
                  griddash: "dash" }`
     -  if chosen yes/no  for `gridXAxis`/`gridYAxis` set `showgrid: true/false` in the layout attribute 
     -  the grid line style is accessed with `griddash:"{gridLineStyleXAxis/gridLineStyleYAxis}"`

 - [ ] Add the `LayoutProperties` component to the  index.js

**Comment by JessicaLoers** [comment]
**Well done, Team 🎉**
Just a small note regarding the value proposition_

Consider to refine the value proposition to focused on the user's need and the action.
**As a user** _[role]_
**I want to** _[action]_
**So that I can** _[value / user benefit]_

_Example_

**As a user**,
**I want to** customise the appearance of charts by enabling grids on the x and y axes,
**So that I can** enhance the readability and precision of data visualisation in my charts.
