### ISSUE TITLE
US-1_Upload-and-convert-a-file 

### ISSUE THREAD

**Issue by YavorLalev** [catdieval/capstone-plotdata#3]
# Upload a CSV file and convert it to an array of objects

## Value proposition

As a user
I want to upload my csv file with data inside
So that I can finally generate a plot.

## Description

![Wireframe User-Story-1bis](https://github.com/catdieval/capstone-plotdata/assets/148149765/80a8a0b7-f04b-4aeb-b5ab-b0fd11fc7046)

## Acceptance criteria

- [x] Title at the top with the name of the website and a logo.
- [x] Heading with text "Step 1: Upload a CSV file to get the data.".
- [x] Paragraph with text "Notes: the file should have a header. The file should be comma-delimited and the decimal separator for numbers should be a period (.). If the file contains missing values, then replace these values in the file by null.".
- [x] A button with a text "Choose a file" which starts the upload process and the default text "no file chosen" is displayed below.
- [x] A button with text "Submit" which is disabled by default and becomes enabled once the upload is successful.
- [x] The elements do not extend to each end of the page but are centered in the middle.
- [x] Clicking the "Choose a file" button opens an upload window  where the user can select a file with a csv extension.
- [x] Once the file is uploaded the filename gets displayed.
- [x] Clicking the "Submit" button displays an alert with the text "File processed successfully".

## Tasks

- [x] Create a new feature branch - upload-data.
- [x] Create the global styles
- [x] Create an asset folder and put inside the image for the logo of the website.
- [x] Create a Components folder with:
  - [x] Title component including the logo image.
  - [x] Layout component which includes the title.
  - [x] Integrate the Layout component in the \_app.js
  - [x] Button component
  - [x] CenteredDiv component.
  - [x] Heading component
  - [x] Paragraph component
  - [x] StyledInputTypeSubmit component 
  - [x] FileUploader component with logic from the FileUploader.js file in https://codesandbox.io/p/sandbox/test-upload-conversion-csv-4-cfd2zh?file=%2Fsrc%2FFileUploader.js%3A1%2C1.
  - [x] CorrectArrays component using the logic from the CorrectArrays.js file in https://codesandbox.io/p/sandbox/test-upload-conversion-csv-4-cfd2zh?file=%2Fsrc%2FCorrectArrays.js%3A5%2C1.
  - [x] UploadData component
    - [x] Install these libraries: convert-csv-to-array, convert-string-to-number and use-local-storage-state.
    - [x] Add const { convertCSVToArray } = require("convert-csv-to-array");
    - [x] Declare a state for the variable keynames using useLocalStorageState with a default value set to [].
    - [x] Declare a state for the variable vals using useLocalStorageState with a default value set to [].
    - [x] Declare a state for the variable fileObj using useState with an initial value set to {}. This will contain the object representing the uploaded file.
    - [x] Declare a state for the variable isUploaded using useState with an initial value set to false. This variable will contain the status about the upload and will serve to enable or disable the input of type "submit".
    - [x] Declare a handleFile function taking file as argument. The function sets the setFileObj to file and sets the setIsUploaded to true.
    - [x] Declare a fileName variable set to fileObj.name.
    - [x] Declare a handleSubmit function which takes event as argument and does event.preventDefault().
    - [x] Declare a handleConversion function which takes the logic from: https://codesandbox.io/p/sandbox/test-upload-conversion-csv-4-cfd2zh?file=%2Fsrc%2FApp.js%3A48%2C1
    - [x] The function returns, within a fragment, the Heading component, the Paragraph component and a form element.
    - [x] Inside the form element is nested the CenteredDiv component, and inside of it, the FileUploader component and the StyledInputTypeSubmit component. 
    - [x] The FileUploader component takes the handleFile as prop.
    - [x] The form element takes handleSubmit as prop to the onSubmit attribute.
    - [x] The StyledInputTypeSubmit component takes "Submit" for the value attribute and !isUploaded for the disable attribute and handleConversion as prop for the Onlick attribute.
  - [x] The Homepage function in index.js file returns the UploadData component.
