### ISSUE TITLE
US-12-Layout-Range-Properties

### ISSUE THREAD

**Issue by MariaAdner** [catdieval/capstone-plotdata#30]
# Range Properties

## Value description
As a user 
I want to adjust the range of the x-and y-axis 
So that I can have a detailed look of my data. 

## Description

![Image](https://github.com/catdieval/capstone-plotdata/assets/148491107/dfaf868e-16ac-4c41-be83-14c79400b765)

## Acceptance Criteria

- [x]  Paragraph with text "Range of values for axes:".
- [x]  User can set the range of values separately for the x- and y-axis from a list with radio-buttons ("yes, normal range"/"yes, reversed range"/"no, set minimum and maximum").
- [x] Only when the user has chosen the "no, set minimum and maximum" option in at least one of the menus above:
    - [x] Paragraph with text "Minimum and maximum values for ax(es)".
    - [x] User can set the minimum and maximum values separately for the x- and y-axis: one input of type "number" for the minimum value, one input of type "number" for the maximum value.

## Tasks

- [x] Create a feature branch "Range-properties".

- [x] Create a ` InputTypeNumber` component:
  - [x] Function with props `idString`, `placeholderString`,  `onChange`.
  - [x] Returns `label` and `input` elements.
  
- [x] Create a `RangeProperties` component:
   - [x] Store the values (states) for  rangeXAxis , rangeYAxis, minXAxis, minYAxis, maxXAxis  and maxYAxis into an object
   - [x] Create a useState called range and use the object as initial state
   - [x] Declare a handle function that reassigns values with spread operator and [e.target.name]: e.target.value
   - [x] Return: `Paragraph`, `InputTypeNumber` and `InputTypeRadio` components in the appropriate order and text described in the acceptance criteria.
   
- [x]  In the index.js, add the `RangeProperties` component to the return (before Plotting).

**Comment by JessicaLoers** [comment]
**Nice** 👍
