### ISSUE TITLE
US-13-Layout-Log-Scale-Properties

### ISSUE THREAD

**Issue by MariaAdner** [catdieval/capstone-plotdata#31]
# Log Scale Properties

## Value description
As a user 
I want to choose the scale for the x-and y-axis (linear or logarithmic)
So that I can improve the visualisation of my data if I have very large/very small numbers. 

## Description

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/0b5e493f-6efa-4225-91da-52af7bc77910)

## Acceptance Criteria

- [x] Paragraph with text "Logarithmic scale for axes:". At the right of the paragraph is an "Info" button.
- [x] When the user clicks on the "Info" button, a dialogue with a "x" button gets displayed. The dialogue has for text the text about log scale shown in the wireframe.
- [x] When the user clicks on the "x" button, the dialogue closes.
- [x] User can decide to have a logarithmic scale separately for the x- and y-axis by using radio-buttons ("yes"/"no, use a linear scale").

## Tasks

- [x] Create a feature branch "Log-scale-properties".
- [x] Create a `DialogBox` component:
  - [x] Use the Material-Ui library: `npm install @mui/material @mui/icons-material`.
  - [x] Import the Dialog, IconButton and CloseIcon components from the Material Ui library.
  - [x] Declare a `useState` for `openDialog`.
  - [x] Declare a `handleOpenDialog` function ->  sets `setOpenDialog` function true.
  - [x] Declare a `handleCloseDialog` function -> sets `setOpenDialog` function false. 
  - [x] Return: `Button` (with onClick = handleOpenDialog), `Dialog` (with onClose = handleCloseDialog, open = openDialog ), CloseIcon, IconButton (aria-label = "close" and onClick = handleCloseDialog) and Paragraph with the text described in the acceptance criteria/wireframe.
- [x] Create a  `LogRangeProperties` component:
  - [x] Declare the `useState` and handle functions for:  `logXAxis`, `logYAxis`, `handleLogXAxis` and `handleLogYAxis`.
 
   - [x] Return:  `Paragraph`, `DialogBox` and `InputTypeRadio` components in the appropriate order and text described in the acceptance criteria 

- [x] In the index.js, add the `LogScaleProperties` component to the return (before Plotting).
