### ISSUE TITLE
US-14-Layout-Properties

### ISSUE THREAD

**Issue by catdieval** [catdieval/capstone-plotdata#32]
# Layout Properties

## Value description

As a user 
I want to adjust the layout of my plot 
So that I can have a clearly represented plot of my data.

## Description

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/d1ff2adb-9cfd-43b8-b4ee-70244bc20dfd)

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/82be2238-277e-465a-9553-36ac85fa5025)

## Acceptance criteria

- [x] Heading with text "Layout properties".
- [x] GridProperties component.
- [x] RangeProperties component.
- [x] LogScaleProperties component.
- [x] "Next" button which stays disabled until the user has entered values in all the fields. Clicking on the button displays an alert message with text "You have selected the layout properties.".
- [x] The plot gets updated with the layout properties.

## Tasks

- [x] Create a new feature branch "Layout-properties".

- [x] Create a `LayoutProperties` component.
  - [x] Write a `handleSubmit function` which does event.preventDefault().
  - [x] Declare a `handleLayoutProperties` function with an alert message.
  - [x] Declare a `notCompletedLayoutProperties` function to disable the "Next" button until the user has selected values in all menus.
  - [x] Returns: `Heading` and `form` element.
  - [x] The form takes the `handleSubmit` function as prop to the `onSubmit` attribute.
  - [x] Inside `form`: `GridProperties`, `RangeProperties`, `LogScaleProperties` and `InputTypeSubmit`.
  - [x] The `InputTypeSubmit` component has "Next" as value to the value attribute, the handleLayoutProperties function as value to the `onClick` attribute and `notCompletedLayoutProperties()` function as value to the disabled attribute.

- [x] In the index.js, add the `LayoutProperties` component to the return (before `Plotting`) and remove GridProperties, RangeProperties and LogScaleProperties from the return.

- [x] In the `Plotting` component, access the `grid` , `range`,`logXAxis` and `logYAxis` variables.
  - [x] Use these variables in the conditional rendering.
  - [x] Use these variables in the `layout` attribute in the Plot component.
