### ISSUE TITLE
DS-state management

### ISSUE THREAD

**Issue by YavorLalev** [catdieval/capstone-plotdata#33]
## Value proposition

As a developer 
I need to reduce the number of useStates 
to have an overall well structured state management.

## Acceptance Criteria
- [x] The states of all components from Step 4 to Step 6 are summarized into one single state. 

## Tasks

- [x]  Create a feature branch `state-management`.
- [x] In general: 

     1.  Create an object for the initial values: `const initialvalues ={state1:"", state2:"", state3:""}`
     2. Create a state: `const [data, setData] = useState(initialvalues)`
     3. Add an `handleChange`: `function handleChangeData(event) {setData({ ...data, [event.target.name]: event.target.value })}`

- [x] Put all the states for the following components: 

    - `XandYLabelsGraph`
    - `GraphTitle`
    -   `BarProperties`
    -   `LineProperties` 
    -   `MarkerProperties`
    -  `GridProperties`
    - `RangeProperties`
    - `LogScaleProperties`
    
    into one state variable called  `settings`.

- [x] Adjust all components + the `Plotting` component.

**Comment by PaulJohannFlade** [comment]
Great improvement. Functionality is good. LGTM 👍
