### ISSUE TITLE
US-17_Stepper-navigation

### ISSUE THREAD

**Issue by YavorLalev** [catdieval/capstone-plotdata#34]
# Stepper Navigation

## Value proposition
As a user 
I want to have a nice and user friendly stepper navigation 
So that I can navigate through the steps.

## Description

![Image](https://github.com/catdieval/capstone-plotdata/assets/148149765/3ce1fb69-29a8-4a68-b6b5-faa9bb79acaf)

## Acceptance criteria

- [x] On the page the user sees a vertical stepper (navigation bar) which allows the user to progress through each step in sequence.
- [x] The vertical stepper is positioned on the left side of the page.
- [x] There is a button labeled "Next" that allows the user to navigate to the next step. It is enabled only after the user selects all of the options given.
- [x] There is also a button labeled "Back" that allows the user to go back to the previous step. It is shown after the first step was completed.
- [x] The button icons in the navigation bar are showing the number of the step by default.
- [x] After the user has completed a single step, the stepper icon shows a check mark for a successfully completed action.
- [x] The user can also navigate to a single step back at any stage by clicking on the step icons.
- [x] At the last step there is a button labeled "Finish" which allows the user to submit the values selected in the layout properties.

## Tasks

- [x] Create a new feature branch "stepper-navigation".
- [x] Create a `Step` component which renders a circular button (showing an icon) and a label.
- [x] Create a `Navigation` component:
  - [x] Map over the `arrayOfSteps` and render a `Step` component for each step.
  - [x] Add the `Button` component to create "Next", "Back" and "Finish" buttons. 
  - [x] Create a `useState` for the active step.
  - [x] Write handle functions for the next and the previous operations for the buttons.
- [x] Create a `AllSteps` component:
  - [x] Add the `UploadData`,`ListOfCharts`,`ChooseVariables`,`XandYLabelsGraph`,`GraphTitle` and `PlottingProperties` components to the return.
  - [x] Render conditionally every component corresponding to the active step.
  - [x] Add to the `Navigation` component and map over the `arrayOfSteps` to render the `AllSteps` component for each step.
  
- [x] Implement the logic that changes the button icon in the navigation bar if the step is already completed.
- [x] Create new page `steps.js`.
- [x] Render the `Navigation` component into `steps.js`
- [x] Remove `UploadData`,`ListOfCharts`,`ChooseVariables`,`XandYLabelsGraph`,`GraphTitle` and `PlottingProperties`  from index.js.
- [x] Refactor the code in all components.
- [x] Apply appropriate styling for the stepper.
