### ISSUE TITLE
US-x_Add-more-y-variables

### ISSUE THREAD

**Issue by YavorLalev** [catdieval/capstone-plotdata#35]
# Add more y-variables

## Value Proposition
As a user I want to add another dataset to the same plot 
so I can plot two or more curves.

## Description

![Image](https://github.com/catdieval/capstone-plotdata/assets/148491107/0bf12799-8114-4cf9-a870-448d6467576a)

## Acceptance Criteria
- [ ] A "+" button to add a new y variable. 
- [ ] Clicking on the "+" button displays a dropdown menu where the user can select an option and displays a "x" icon button.
- [ ] When a new dropdown menu has been added, then an additional input of type "text" is displayed where the user can type the name of the variable, for example y2, y3, .... There is a placeholder text to guide the user. 
- [ ] Clicking on the "x" button deletes the dropdown menu.

## Tasks

- [ ] Create a new feature branch "add-y-variables"
- [ ] In the `ChooseVariable`- component:
  - [ ] after the DropDownMenu for the first y-axis add a `Paragraph` and  a +  `button`:
    - [ ] onClick renders a new DropDownMenu, changes the labelString of the first DropDownMenu from y to y1
    - [ ] 
  - [ ] 
  - [ ] The value of this input of type "text" is fed to the idString prop in the DropDownMenu component.
