### ISSUE TITLE
US - connect pages

### ISSUE THREAD

**Issue by YavorLalev** [catdieval/capstone-plotdata#56]
# Connect pages

## Value proposition
As a user 
I want to have buttons
So that I can navigate between pages.

## Description
- [x] At the bottom on the  Start page the user clicks on `Get Started` button and is being redirected to the `/steps` page.
- [x] At the `steps` page there is a Stepper navigation with all the steps in sequence.
- [x] On top of the stepper in the middle there is a `Back` button which redirects back to the `Start` page.
- [x] At the `steps` page after the user has completed the last step then pops up at the bottom of the stepper a button `Plot`.
- [x] At the `Plot` page the users sees a Graph with a `Back` button at the bottom.

## Acceptance criteria

- [x] On the  Start page the user sees a `Get Started` button.
- [x] Clicking on it the user is redirected to the page `/steps`.
- [x] On the page `/steps` there is a `Back` button which redirects the user back to the `Start page`.
- [x] On the page `/steps` there is a `Plot` button which redirects to the page `/plot`.
- [x] On the page `plot` there is a `Back` button which redirects to the page `/steps`.

## Tasks
- [x] Create a feature branch `connect-pages`.
- [x] In `index.js`:
  - [x] import `useRouter` from next.
  - [x] Create a `handleGetStarted` function for the `Get started` button which redirects to the `/steps` page.
 - [x] In the `Navigation` component: 
   - [x] Import `useRouter`
   - [x] Create a `Home` button.
   - [x]  Create a `handleBackStartPage` function for the `Home` button which redirects to the `Start` page.
   - [x] Create a `Plot` button and write a condition to render this button only after the user has clicked on the last step.
   - [x]  Create a `handlePlotNavigation` function for the `Plot` button which redirects to the `/plot` page.
 - [x] Create in pages `plot.js`.
    - [x] Import `useRouter`.
   - [x] write a function `Plot` which renders `Plotting component`, `Back` button to redirects to `/steps`.
   - [x] Write a `handleBack` function for the `Back` button.
