### ISSUE TITLE
US-4_Plotting

### ISSUE THREAD

**Issue by catdieval** [catdieval/capstone-plotdata#7]
# Plotting

## Value Proposition
As a user I want to see the plot of my uploaded data. 

## Description

![Image](https://github.com/catdieval/capstone-plotdata/assets/148444485/8778b411-8b59-431a-97b1-7788d253a4e4)

## Acceptance Criteria

- [x] Logo and title at the top of page.
- [x] Paragraph with text "You can interact with the graph by using the functions at the top of the graph.".
- [x] Plot of the uploaded data.

## Tasks

- [x] Create a new feature branch "Plotting". 
- [x] Install these libraries: react-plotly and plotly.
- [x] useState for the clickedChartType variable in the App.js
- [x] Move handleChartType function to App.js
- [x] Pass down clickedChartType and handleChartType as props.
- [x] Create a Plotting component.
  - [x] Hard code XVariable and YVariable.
  - [x] Find which object in chartArray has the key "name" matching with the value of clickedChartType.
  - [x] Declare a selectedMode variable and a selectedType variable and set their values to the values of the "mode" key and the "type" key found in the previous step.  
  - [x] The function returns, within a fragment, the Paragraph component and the CenteredDiv component.
  - [x] Inside CenteredDiv is nested the Plot component.
  - [x] The Paragraph has for text "You can interact with the graph by using the functions at the top of the graph.".
  - [x] The Plot has the data attribute set to
        `{[
        {
          x: XVariable,
          y: YVariable,
          mode: selectedMode,
          type: selectedType,        },
  ]}`.
  - [x] The Plot has the layout attribute set to
        `{{
        xaxis: {
          showline: true,
          ticks: "outside",
        },
        yaxis: {
          showline: true,
          ticks: "outside",
        },
        width: 600,
        height: 500,
      }}`.
  - [x] The Plot has the config attribute set to
        `{{
        displayModeBar: true,
        modeBarButtonsToRemove: ["lasso2d", "select2d", "pan2d"],
 }}`.
- [x] Add the Plotting component to the index.js file.//

**Comment by MerleMak** [comment]
nice!!
